spring:
  application:
    name: Spring-alibaba-example
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/your_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: your_password
  ai:
    dashscope:
      api-key: ${qwen.apiKey}
      chat:
        options:
          model: qwen-plus

server:
  port: 8567
  servlet:
    context-path: /api

qwen:
  apiKey: your-apikey

# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.springalibabaexample.controller

# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn


